apiVersion: apps/v1
kind: Deployment
metadata:
  name: localvm
  labels:
    app: localvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localvm
  template:
    metadata:
      labels:
        app: localvm
    spec:
      containers:
        - image: phanikumarps/localvm:alphav3
          imagePullPolicy: Always
          name: localvm
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: localvm
  labels:
    app: localvm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: localvm
